In [2]:
from source.utils import read_yaml_file
import pandas as pd

In [11]:
# train_csv = r'D:\ineuron\ML_Internship_projects\Back_order_prediction_end2end\artifact\10_14_2023_16_30_29\data_ingestion\ingested\train.csv'
train_csv =r'D:\ineuron\ML_Internship_projects\Back_order_prediction_end2end\artifact\10_18_2023_14_32_23\data_ingestion\ingested\train.csv'
test_csv = r'D:\ineuron\ML_Internship_projects\Back_order_prediction_end2end\artifact\10_14_2023_16_30_29\data_ingestion\ingested\test.csv'

In [12]:
pd.read_csv(train_csv)

            sku  national_inv  ...  went_on_backorder  lead_time
0       1133363           679  ...                 No        8.0
1       1980576             6  ...                 No        8.0
2       1778473           149  ...                 No        9.0
3       1878365             2  ...                 No        4.0
4       2147013             5  ...                 No       12.0
...         ...           ...  ...                ...        ...
851994  1593800            31  ...                 No        2.0
851995  1694412          1709  ...                 No       12.0
851996  2108053            16  ...                 No        2.0
851997  1501007            39  ...                 No        2.0
851998  1850526            73  ...                 No        2.0

[851999 rows x 23 columns]