In [2]:
from source.utils import read_yaml_file
import pandas as pd

In [10]:
# train_csv = r'D:\ineuron\ML_Internship_projects\Back_order_prediction_end2end\artifact\10_14_2023_16_30_29\data_ingestion\ingested\train.csv'
train_csv =r'D:\ineuron\ML_Internship_projects\Back_order_prediction_end2end\artifact\10_15_2023_16_37_25\data_ingestion\ingested\train.csv'
test_csv = r'D:\ineuron\ML_Internship_projects\Back_order_prediction_end2end\artifact\10_14_2023_16_30_29\data_ingestion\ingested\test.csv'

In [9]:
pd.read_csv(train_csv)

        national_inv  lead_time  ...  ppap_risk  stop_auto_buy
0                 30        2.0  ...         No            Yes
1                  7        8.0  ...        Yes            Yes
2                963        8.0  ...         No             No
3                  9        8.0  ...         No            Yes
4                  0        3.0  ...         No            Yes
...              ...        ...  ...        ...            ...
851994            45        4.0  ...         No            Yes
851995         13193        8.0  ...         No            Yes
851996           239        8.0  ...         No            Yes
851997            63        8.0  ...         No            Yes
851998           202        8.0  ...         No            Yes

[851999 rows x 15 columns]